### ISSUE TITLE
Whisper initialization failed - no media provider

### ISSUE THREAD

**Issue by weixiongmei** [nettlep/magic#14]
Running the Whisper on a MacbookPro, which has built-in camera, I also attached a USB camera as well, why is can't find the cameras?

**Comment by nettlep** [comment]
I have just tested this myself locally and this works. Perhaps this is a permissions issue? Check System Settings -> Privacy & Security -> Camera. Look to ensure Abra is in the list and enabled.

If this isn't the case, can you provide any other diagnostic information?

**Comment by weixiongmei** [comment]
@nettlep thanks, fixed. Is it possible to port the project to C/C++ or C# as a minimum library(Like just passing the pixels data of a frame)? I would like to use it on a ESP32 MCU. I can pay if you don't mind to help. Can you help please? Thank you!!!

**Comment by alexey55501** [comment]
> [@nettlep](https://github.com/nettlep) thanks, fixed. Is it possible to port the project to C/C++ or C# as a minimum library(Like just passing the pixels data of a frame)? I would like to use it on a ESP32 MCU. I can pay if you don't mind to help. Can you help please? Thank you!!!

Hey, have you found a solution of porting this project to c++/c# library?

**Comment by weixiongmei** [comment]
> > [@nettlep](https://github.com/nettlep) thanks, fixed. Is it possible to port the project to C/C++ or C# as a minimum library(Like just passing the pixels data of a frame)? I would like to use it on a ESP32 MCU. I can pay if you don't mind to help. Can you help please? Thank you!!!
> 
> Hey, have you found a solution of porting this project to c++/c# library?

Yes I did, but have completely forgot where I put my source codes, because it had been two years now....
