### ISSUE TITLE
Swift Compile Error

### ISSUE THREAD

**Issue by caichunjian520** [nettlep/magic#3]
I just try to run Steve on my mac in Xcode, it says Swift Compiler Error
'aalib.h' file not found (cheader.h)
Could not build Objective-C module 'C_AAlib' (TextUI.swift)

![167501656656913_ pic](https://user-images.githubusercontent.com/17617309/176837927-e0d82297-d620-4c13-a0e5-e05f6217cfbd.jpg)
)

**Comment by nettlep** [comment]
Try `brew install aalib`
