### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Chtwin** [nettlep/magic#4]
I tried to run steve but I encountered a problem.
<img width="510" alt="Screenshot 2022-07-01 at 15 32 12" src="https://user-images.githubusercontent.com/37251146/176905018-3ffaf560-7708-49be-8dbc-c3aac7075fb0.png">
It is written that there are files missing in the directory where there are the demonstration videos.
So I manually added fake videos to see if the code compiles and I got this (My fake videos are simply videos that I renamed with the missing file names in the error message ):
<img width="652" alt="Screenshot 2022-07-01 at 15 37 25" src="https://user-images.githubusercontent.com/37251146/176905603-64d45de6-d63c-4044-a039-03a8270bc6e6.png">
The code compiles but I still have a problem.
Even when I drag and drop a video it does not work, could you help me pls?

**Comment by nettlep** [comment]
Ah, thanks for pointing this out. There are two issues at hand:

1. The first is the build failure. I've pushed an update that resolves this. There were a number of samples that were left out of this published repo (only because they require a lot of space.) I have simply removed their references from the Xcode project.

2. This is a documentation issue (which I will correct soon.) A quick solution is to simply run these two commands from the project's root folder:

```
$ cp decks.json ~/.decks.json
$ cp whisper.conf ~/.whisper.conf
```

**Comment by nettlep** [comment]
I've updated the documentation with further clarification, explaining the cascading loading process of those configuration files. For Steve, the update is here:

https://nettlep.github.io/magic/#gettingupandrunning/meetsteve:thetestbed

**Comment by nettlep** [comment]
@Chtwin  - did you get it working? And if so, were there other issues you needed to work through in order to get it up and running? You're officially the first person to run this besides myself (that I'm aware of) and I want to make sure there aren't further issues/oversights on my part.

**Comment by Chtwin** [comment]
> @Chtwin - did you get it working? And if so, were there other issues you needed to work through in order to get it up and running? You're officially the first person to run this besides myself (that I'm aware of) and I want to make sure there aren't further issues/oversights on my part.

I pulled and executed the commands and everything works with steve. I plan to use all the features because I was working on exactly the same project for a few days but you have already done almost everything. I ordered the camera for my pi zero and I will use everything. I also plan to add features to the application if you are interested in sharing.
I will also 3D print modules to hide the camera in different objects!
If there is any problem I will make reports. I think there is a problem with CardBars on mac M1 but I'm not sure, I'll let you know if there is a problem.

**Comment by nettlep** [comment]
Note that Cardbars will require the same configuration files setup. So if it wasn’t working before, the work you did to get Steve running should resolve any issues with Cardbars.

**Comment by Chtwin** [comment]
<img width="519" alt="Screenshot 2022-07-01 at 19 33 58" src="https://user-images.githubusercontent.com/37251146/176943634-481a15f7-bcd4-488d-9b97-1fb89df23a40.png">
I ran carbars without any other modification and it shows me this

**Comment by nettlep** [comment]
This is expected. Select a code from the `Codes` menu. Use the Image menu to perform operations on that code.

If you have Abra running on a device (with a local server enabled) you can use Abra to scan the code right out of the window.

Also, if you have Steve running and Abra running, you can use Abra to "remote view" the scans from Steve. Just make sure they're on the same network and Abra does not have a local server running.

**Comment by Chtwin** [comment]
Thank you very much. I haven't had time to read everything yet but I will read all the docs and test with the camera on the rapsberry pi. I'll let you know if I have any problem

**Comment by caichunjian520** [comment]
I successfully compile Steve, but there are two issues.
1. Xcode console log prints out error info.
2. There is no window shown when I tap Steve app.

![6171656740540_ pic](https://user-images.githubusercontent.com/17617309/176988199-62a470df-d8d9-4113-9a7b-646255a0f1f1.jpg)
